apiVersion: apps/v1
kind: Deployment
metadata:
  name: kz-commands
  namespace: kaizen
  labels:
    app: kz-commands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kz-commands
  template:
    metadata:
      labels:
        app: kz-commands
    spec:
      containers:
      - name: kaizen-backend
        image: s2bantnd/kaizen_backend:0.0.242
        ports:
        #- containerPort: 3000
        #- containerPort: 4000
        - containerPort: 3000
        - containerPort: 8000
        resources:
          limits:
            memory: 1024Mi
            cpu: "2"
          requests:
            memory: 128Mi
            cpu: "0.2"
        env:
          - name: HTTP_PORT
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: HTTP_PORT
          - name: HTTPS_PORT
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: HTTPS_PORT
          - name: APP_IP
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: APP_IP
          - name: DB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: DB_CONNECTION
          - name: DB_HOST_1
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: DB_HOST_1
          - name: DB_PORT_1
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: DB_PORT_1
          - name: DB_DATABASE_1
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: DB_DATABASE_1
          - name: DB_USERNAME_1
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: DB_USERNAME_1
          - name: DB_PASSWORD_1
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: DB_PASSWORD_1
          - name: SHARE_POINT_USER
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: SHARE_POINT_USER
          - name: SHARE_POINT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: SHARE_POINT_PASSWORD
          - name: BITRIX_URL
            valueFrom:
              secretKeyRef:
                name: kz-secret
                key: BITRIX_URL
---
apiVersion: v1
kind: Service
metadata:
  name: kz-commands
  namespace: kaizen
spec:
  selector:
    app: kz-commands
  #type: LoadBalancer
  type: ClusterIP
  # ports:
  # - protocol: TCP
  #   port: 443
  #   targetPort: 3000
  # ports:
  #   - protocol: TCP
  #     port: 3000
  #     targetPort: 3000
  ports:
  - name: http
    protocol: TCP
    port: 80
    #targetPort: 8080
    targetPort: 8000
  # - name: http
  #   protocol: TCP
  #   port: 80
  #   targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    #targetPort: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: kz-secret
  namespace: kaizen
type: Opaque
data:
  HTTP_PORT: ODAwMAo=
  HTTPS_PORT: MzAwMA==
  APP_IP: MC4wLjAuMA==
  DB_CONNECTION: bXlzcWw=
  DB_HOST_1: MTkyLjE2OC4yLjExOQ==
  DB_PORT_1: MzMwNg==
  DB_DATABASE_1: a2FpemVu
  DB_USERNAME_1: bmFi
  DB_PASSWORD_1: bmFic3Fs
  SHARE_POINT_USER: dGVzdGJpdHJpeEBlc3VoYWkuY29t
  SHARE_POINT_PASSWORD: MTIzNDU2YUFA
  BITRIX_URL: aHR0cHM6Ly9iaXRyaXguZXN1aGFpLm9yZy9yZXN0LzUwNS9nZ2xhemVnd2NvZHJ1aHIzLw==

# stringData:
#   HTTP_PORT: 8000
#   HTTPS_PORT: 3000
#   APP_IP: 0.0.0.0
#   DB_CONNECTION: mysql
#   DB_HOST_1: 192.168.2.119
#   DB_PORT_1: 3306
#   DB_DATABASE_1: kaizen
#   DB_USERNAME_1: nab
#   DB_PASSWORD_1: nabsql
#   SHARE_POINT_USER: testbitrix@esuhai.com
#   SHARE_POINT_PASSWORD: 123456aA@
#   BITRIX_URL: https://bitrix.esuhai.org/rest/505/gglazegwcodruhr3/
